[FIX] ansible-linux-active-directory: Fix bugs & Add Tests
LasLabs/ansible-linux-active-directory pull request #2
Opened 2017-02-22 00:27 UTC by tedsalmon

* Add tests via travis
* Fix bugs with DNS settings and SSSD service status

2017-02-22 00:40 UTC, lasley requested changes

2017-02-22 00:40 UTC, lasley commented on meta/main.yml
> +  license: AGPL
License is Apache 2.0

2017-02-22 00:40 UTC, lasley commented on tasks/dns.yml
> +  service: name=resolvconf state=restarted
newline at EOF

2017-02-23 00:32 UTC, tedsalmon commented
Thanks for the review, @lasley. I have attended to your comments but already squashed them in since it was two minor changes (also, this is an excuse because I totally squashed out on auto-pilot (badpokerface)).

2017-02-23 00:49 UTC, lasley approved these changes

2017-02-23 00:49 UTC, merged